/* ============================================================
   PokECG — DATA: 27 Cardiac Pathologies
   All definitions in ENGLISH
   ============================================================ */

const POKEDEX = [
    { id:1, pokemon:"Pikachu", pokemonImg:"Images/gen1/1pikachu.png",
      patologia:"Sinus Rhythm", gifECG:"Images/Gift_Patologia/Sinus Rhythm.gif",
      audio:"Audio_ECG/1.aac", severity:"normal",
      hr:75, pr:160, qrs:90, rr:"Regular",
      definicion:"Normal rhythm from SA node. Rate 60-100 bpm; regular R-R; upright P before each QRS; PR 0.12-0.20s.",
      diagnostico:"Normal finding. No treatment required.",
      asociadas:"Usually none. Normal variant." },

    { id:2, pokemon:"Slowpoke", pokemonImg:"Images/gen1/2slowpoke.png",
      patologia:"Sinus Bradycardia", gifECG:"Images/Gift_Patologia/Sinus Bradycardia.gif",
      audio:"Audio_ECG/2.aac", severity:"mild",
      hr:45, pr:160, qrs:90, rr:"Regular",
      definicion:"Sinus rhythm with rate < 60 bpm.",
      diagnostico:"Often physiological. Treat if symptomatic (atropine, pacing).",
      asociadas:"Hypothyroidism, medications (beta-blockers), increased vagal tone, sleep apnea." },

    { id:3, pokemon:"Jolteon", pokemonImg:"Images/gen1/3jolteon.png",
      patologia:"Sinus Tachycardia", gifECG:"Images/Gift_Patologia/Sinus Tachycardia.gif",
      audio:"Audio_ECG/3.aac", severity:"mild",
      hr:130, pr:150, qrs:90, rr:"Regular",
      definicion:"Sinus rhythm with rate > 100 bpm. Normal P waves and PR interval.",
      diagnostico:"Treat underlying cause; beta-blockers if inappropriate.",
      asociadas:"Fever, anemia, hyperthyroidism, dehydration, anxiety, exercise." },

    { id:4, pokemon:"Eevee", pokemonImg:"Images/gen1/4eevee.png",
      patologia:"Sinus Arrhythmia", gifECG:"Images/Gift_Patologia/Sinus Arrhythmia.gif",
      audio:"Audio_ECG/4.aac", severity:"normal",
      hr:70, pr:160, qrs:90, rr:"Irregular (phasic)",
      definicion:"Sinus rhythm with varying P-P intervals (phasic with respiration). Variation > 10%.",
      diagnostico:"Benign, normal finding. No treatment required.",
      asociadas:"Usually benign. Common in young people and athletes." },

    { id:5, pokemon:"Abra", pokemonImg:"Images/gen1/5abra.png",
      patologia:"Sinus Exit Block", gifECG:"Images/Gift_Patologia/Sinus Exit Block.gif",
      audio:"Audio_ECG/5.aac", severity:"severe",
      hr:55, pr:160, qrs:90, rr:"Pause (multiple of PP)",
      definicion:"Failure of sinus impulse to exit SA node. Pause is an exact multiple of P-P interval.",
      diagnostico:"Treat underlying cause (drugs, ischemia). Pacing if symptomatic.",
      asociadas:"Drugs (digoxin, beta-blockers), ischemia, myocarditis, aging." },

    { id:6, pokemon:"Snorlax", pokemonImg:"Images/gen1/6snorlax.png",
      patologia:"Sinus Arrest", gifECG:"Images/Gift_Patologia/Sinus Arrest.gif",
      audio:"Audio_ECG/6.aac", severity:"severe",
      hr:50, pr:160, qrs:90, rr:"Pause (not multiple)",
      definicion:"Temporary cessation of sinus node activity. P waves disappear for seconds to minutes.",
      diagnostico:"Treat cause. Pacemaker if symptomatic.",
      asociadas:"Sick sinus syndrome, sleep apnea, drugs, ischemia, aging." },

    { id:7, pokemon:"Raichu", pokemonImg:"Images/gen1/7raichu.png",
      patologia:"NSR with PAC", gifECG:"Images/Gift_Patologia/NSR with PAC.gif",
      audio:"Audio_ECG/7.aac", severity:"normal",
      hr:78, pr:160, qrs:90, rr:"Irregular (early beat)",
      definicion:"Premature atrial contraction. Early P wave followed by narrow QRS, often with non-compensatory pause.",
      diagnostico:"Usually benign. Beta-blockers if symptomatic.",
      asociadas:"Stress, caffeine, alcohol, hyperthyroidism, lung disease." },

    { id:8, pokemon:"Arcanine", pokemonImg:"Images/gen1/8arcanine.png",
      patologia:"SVT", gifECG:"Images/Gift_Patologia/Supraventricular Tachycardia.gif",
      audio:"Audio_ECG/8.aac", severity:"moderate",
      hr:180, pr:120, qrs:85, rr:"Regular",
      definicion:"Supraventricular tachycardia. Regular narrow-complex tachycardia > 150 bpm originating above the ventricles.",
      diagnostico:"Vagal maneuvers or Adenosine. Beta-blockers/ablation long-term.",
      asociadas:"Wolff-Parkinson-White syndrome, caffeine, stress, alcohol." },

    { id:9, pokemon:"Gengar", pokemonImg:"Images/gen1/9gengar.png",
      patologia:"Atrial Fibrillation", gifECG:"Images/Gift_Patologia/Atrial Fibrillation.gif",
      audio:"Audio_ECG/9.aac", severity:"moderate",
      hr:110, pr:0, qrs:90, rr:"Irregularly irregular",
      definicion:"Irregularly irregular R-R with no distinct P waves. Fibrillatory waves may be seen.",
      diagnostico:"Rate control, rhythm control, anticoagulation.",
      asociadas:"Hypertension, heart failure, valvular disease, hyperthyroidism, sleep apnea, obesity, alcohol." },

    { id:10, pokemon:"Lapras", pokemonImg:"Images/gen1/10lapras.png",
      patologia:"Atrial Flutter", gifECG:"Images/Gift_Patologia/Atrial Flutter.gif",
      audio:"Audio_ECG/10.aac", severity:"moderate",
      hr:150, pr:0, qrs:90, rr:"Regular (2:1)",
      definicion:"Sawtooth flutter waves (f waves) in leads II, III, aVF. Atrial rate 250-320 bpm; ventricular rate often 150 bpm.",
      diagnostico:"Similar to AFib. Catheter ablation effective.",
      asociadas:"COPD, heart failure, valvular disease, hyperthyroidism, post-surgery." },

    { id:11, pokemon:"Growlithe", pokemonImg:"Images/gen1/11growlithe.png",
      patologia:"Paced Atrial", gifECG:"Images/Gift_Patologia/Paced Atrial.gif",
      audio:"Audio_ECG/11.aac", severity:"normal",
      hr:70, pr:160, qrs:90, rr:"Regular",
      definicion:"Pacemaker stimulus (spike) immediately before P wave, followed by normal QRS.",
      diagnostico:"Indicates atrial pacing. Manage underlying pacemaker indication.",
      asociadas:"Sinus node dysfunction, AV block, post-surgery, medications." },

    { id:12, pokemon:"Clefairy", pokemonImg:"Images/gen1/12clefairy.png",
      patologia:"NSR with 1° AVB", gifECG:"Images/Gift_Patologia/NSR with 1° AVB.gif",
      audio:"Audio_ECG/12.aac", severity:"normal",
      hr:75, pr:240, qrs:90, rr:"Regular",
      definicion:"Sinus rhythm with PR interval > 0.20s. Conduction slowed without skipped beats.",
      diagnostico:"Usually benign; monitor progression.",
      asociadas:"Drugs (beta-blockers, digoxin), ischemia, myocarditis, aging." },

    { id:13, pokemon:"Dragonair", pokemonImg:"Images/gen1/13dragonair.png",
      patologia:"2° AVB Type I", gifECG:"Images/Gift_Patologia/2° AVB Type I.gif",
      audio:"Audio_ECG/13.aac", severity:"moderate",
      hr:60, pr:220, qrs:90, rr:"Irregular (dropped QRS)",
      definicion:"Progressive PR prolongation until a dropped QRS (Wenckebach).",
      diagnostico:"Often benign. Treat if symptomatic.",
      asociadas:"Athletes, inferior MI, drugs (beta-blockers, digoxin), myocarditis." },

    { id:14, pokemon:"Hypno", pokemonImg:"Images/gen1/14hypno.png",
      patologia:"2° AVB Type II", gifECG:"Images/Gift_Patologia/2° AVB Type II.gif",
      audio:"Audio_ECG/14.aac", severity:"severe",
      hr:55, pr:180, qrs:110, rr:"Irregular (sudden drop)",
      definicion:"Sudden dropped QRS without prior PR prolongation (Mobitz II).",
      diagnostico:"High risk. Requires permanent pacemaker.",
      asociadas:"Anterior MI, fibrosis of conduction system, aging, cardiomyopathy." },

    { id:15, pokemon:"Flareon", pokemonImg:"Images/gen1/15flareon.png",
      patologia:"2° AVB 2:1", gifECG:"Images/Gift_Patologia/2° AVB 2 1.gif",
      audio:"Audio_ECG/15.aac", severity:"severe",
      hr:50, pr:180, qrs:100, rr:"Regular (2:1)",
      definicion:"Every other P wave conducted (2 P waves per 1 QRS).",
      diagnostico:"Type II needs pacing.",
      asociadas:"Anterior MI, fibrosis, cardiomyopathy, drugs." },

    { id:16, pokemon:"Charmeleon", pokemonImg:"Images/gen1/16charmeleon.png",
      patologia:"3° AV Block", gifECG:"Images/Gift_Patologia/3° AV Block.gif",
      audio:"Audio_ECG/16.aac", severity:"severe",
      hr:35, pr:0, qrs:120, rr:"Regular (dissociated)",
      definicion:"Complete dissociation between P waves and QRS.",
      diagnostico:"Permanent pacemaker.",
      asociadas:"Anterior MI, fibrosis, cardiomyopathy, drugs, Lyme disease." },

    { id:17, pokemon:"Alakazam", pokemonImg:"Images/gen1/17alakazam.png",
      patologia:"NSR with PJC", gifECG:"Images/Gift_Patologia/NSR with PJC.gif",
      audio:"Audio_ECG/17.aac", severity:"mild",
      hr:78, pr:0, qrs:90, rr:"Irregular (early beat)",
      definicion:"Premature junctional contraction. Narrow QRS, inverted/absent P wave (retrograde).",
      diagnostico:"Usually benign.",
      asociadas:"Digoxin toxicity, inferior MI, myocarditis, post-surgery." },

    { id:18, pokemon:"Exeggutor", pokemonImg:"Images/gen1/18exeggutor.png",
      patologia:"Junctional Rhythm", gifECG:"Images/Gift_Patologia/Junctional Rhythm.gif",
      audio:"Audio_ECG/18.aac", severity:"mild",
      hr:50, pr:0, qrs:90, rr:"Regular",
      definicion:"Rhythm originating from AV junction. Rate 40-60 bpm. Absent or inverted P waves.",
      diagnostico:"Treat if symptomatic (atropine, pacing).",
      asociadas:"Digoxin toxicity, inferior MI, myocarditis, hyperkalemia." },

    { id:19, pokemon:"Slowbro", pokemonImg:"Images/gen1/19slowbro.png",
      patologia:"Accel Junctional", gifECG:"Images/Gift_Patologia/Accelerated Junctional.gif",
      audio:"Audio_ECG/19.aac", severity:"mild",
      hr:80, pr:0, qrs:90, rr:"Regular",
      definicion:"Junctional rhythm with rate 60-100 bpm.",
      diagnostico:"Often seen in digitalis toxicity or ischemia. Treat underlying cause.",
      asociadas:"Digoxin toxicity, ischemia, post-surgery, myocarditis." },

    { id:20, pokemon:"Poliwhirl", pokemonImg:"Images/gen1/20poliwhirl.png",
      patologia:"Junctional Tachy", gifECG:"Images/Gift_Patologia/Junctional Tachycardia.gif",
      audio:"Audio_ECG/20.aac", severity:"moderate",
      hr:130, pr:0, qrs:90, rr:"Regular",
      definicion:"Junctional rhythm with rate > 100 bpm. Narrow QRS, no visible P waves.",
      diagnostico:"Treat underlying cause (ischemia, dig toxicity).",
      asociadas:"Digoxin toxicity, ischemia, cardiomyopathy, post-surgery." },

    { id:21, pokemon:"Seaking", pokemonImg:"Images/gen1/21seaking.png",
      patologia:"Wandering Pacemaker", gifECG:"Images/Gift_Patologia/Wandering Pacemaker.gif",
      audio:"Audio_ECG/21.aac", severity:"normal",
      hr:70, pr:160, qrs:90, rr:"Slightly irregular",
      definicion:"Pacemaker site shifts between SA node, atria, and AV junction. Varying P wave morphology and PR intervals.",
      diagnostico:"Usually benign.",
      asociadas:"Usually benign. COPD, hypoxia, drugs." },

    { id:22, pokemon:"Wigglytuff", pokemonImg:"Images/gen1/22wigglytuff.png",
      patologia:"NSR with PVC", gifECG:"Images/Gift_Patologia/NSR with PVC.gif",
      audio:"Audio_ECG/22.aac", severity:"moderate",
      hr:80, pr:160, qrs:90, rr:"Irregular (early wide beat)",
      definicion:"Premature ventricular contraction. Wide, bizarre QRS, no preceding P wave.",
      diagnostico:"Beta-blockers if symptomatic.",
      asociadas:"Ischemia, cardiomyopathy, hypoxia, caffeine, stress, electrolyte imbalance." },

    { id:23, pokemon:"Blastoise", pokemonImg:"Images/gen1/23blastoise.png",
      patologia:"Idioventricular", gifECG:"Images/Gift_Patologia/Idioventricular Rhythm.gif",
      audio:"Audio_ECG/23.aac", severity:"severe",
      hr:30, pr:0, qrs:140, rr:"Regular",
      definicion:"Ventricular escape rhythm. Rate 20-40 bpm, wide QRS.",
      diagnostico:"Pacing if symptomatic.",
      asociadas:"Severe ischemia, complete AV block, drug toxicity, end-stage heart disease." },

    { id:24, pokemon:"Exeggcute", pokemonImg:"Images/gen1/24exeggcute.png",
      patologia:"Accelerated IVR", gifECG:"Images/Gift_Patologia/Accelerated IVR.gif",
      audio:"Audio_ECG/24.aac", severity:"severe",
      hr:70, pr:0, qrs:130, rr:"Regular",
      definicion:"Ventricular rhythm with rate 40-100 bpm.",
      diagnostico:"Usually benign, monitor.",
      asociadas:"Reperfusion post-MI, digoxin toxicity, cardiomyopathy." },

    { id:25, pokemon:"Fearow", pokemonImg:"Images/gen1/25fearow.png",
      patologia:"VTach", gifECG:"Images/Gift_Patologia/Ventricular Tachycardia.gif",
      audio:"Audio_ECG/25.aac", severity:"critical",
      hr:180, pr:0, qrs:160, rr:"Regular",
      definicion:"Wide QRS tachycardia (>100 bpm) originating from ventricles.",
      diagnostico:"Unstable: synchronized cardioversion. Stable: amiodarone/lidocaine.",
      asociadas:"Ischemic heart disease, cardiomyopathy, valvular disease, electrolyte imbalance, drugs." },

    { id:26, pokemon:"Golduck", pokemonImg:"Images/gen1/26golduck.png",
      patologia:"VFib", gifECG:"Images/Gift_Patologia/Ventricular Fibrillation.gif",
      audio:"Audio_ECG/26.aac", severity:"critical",
      hr:0, pr:0, qrs:0, rr:"Chaotic",
      definicion:"Chaotic, unorganized electrical activity; no identifiable QRS complexes.",
      diagnostico:"Defibrillation + CPR immediately.",
      asociadas:"Ischemic cardiomyopathy, hypertrophic cardiomyopathy, dilated cardiomyopathy, electrolyte abnormalities, acidosis, hypoxemia, myocardial ischemia." },

    { id:27, pokemon:"Dragonite", pokemonImg:"Images/gen1/27dragonite.png",
      patologia:"Paced Ventricular", gifECG:"Images/Gift_Patologia/Paced Ventricular.gif",
      audio:"Audio_ECG/27.aac", severity:"critical",
      hr:70, pr:0, qrs:150, rr:"Regular",
      definicion:"Pacing spike immediately before a wide QRS complex.",
      diagnostico:"Indicates ventricular pacing.",
      asociadas:"Complete AV block, sinus node dysfunction, post-surgery." }
];

function getPathology(id) {
    return POKEDEX.find(p => p.id === id);
}

function getPathologyByName(name) {
    return POKEDEX.find(p => p.patologia === name);
}